version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POKEAPI_URL=https://pokeapi.co/api/v2/pokemon/
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - POKEAPI_URL=https://pokeapi.co/api/v2/pokemon/
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"